# Generated by Django 2.2.13 on 2021-08-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
